config/routes.rb
QidiqImporter::Application.routes.draw do
  resources :feedback_groups do
    post 'call_api_import', on: :member, as: :call_api_import
  end

  devise_for :users

  root :to => 'feedback_groups#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :manage, FeedbackGroup, user_id: user.id
  end
end

app/models/feedback_group.rb
require 'json'
require 'rest_client'

class FeedbackGroup < ActiveRecord::Base
  QIDIQ_API_URL = 'http://www.qidiq.com/api/query'
  
  attr_accessible :api_key, :explanation, :url
  belongs_to :user
  validates :url, :api_key, :explanation, presence: true
  
  def import_user(email)
    params = {
      import_members: 1, 
      feed_url_path: url,
      explanation_text: explanation,
      api_key: api_key, 
      email_addresses: [email]
    }
    params_json = params.to_json
    http_params = {params: params_json}
    RestClient.post(QIDIQ_API_URL, http_params)
  end
  
  def import_post_url
    root_url
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable#, :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation#, :remember_me
  # attr_accessible :title, :body
  
  has_many :feedback_groups
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/feedback_groups_controller.rb
class FeedbackGroupsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :call_api_import]
  load_and_authorize_resource except: [:index, :call_api_import]
  
  def index
    @feedback_groups = current_user.try(:feedback_groups)
  end

  def show
    @import_post_url = call_api_import_feedback_group_url(@feedback_group)
  end

  def new
  end

  def edit
  end

  def create
    if @feedback_group.save
      redirect_to @feedback_group, notice: 'Feedback group was successfully created.'
    else
      render action: "new"
    end
  end

  def update
    if @feedback_group.update_attributes(params[:feedback_group])
      redirect_to @feedback_group, notice: 'Feedback group was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @feedback_group.destroy
    redirect_to feedback_groups_url
  end
  
  def call_api_import
    feedback_group = FeedbackGroup.find(params[:id])
    if /^[a-zA-Z0-9_\.\+\-]+@[a-zA-Z0-9\-]+\.[a-zA-Z0-9\-\.]+$/.match(params[:email])
      result_string = feedback_group.import_user params[:email]
      result_json = JSON.parse(result_string).symbolize_keys
      result_code = result_json[:error_code]
    else
      result_code = '7'
    end
    if params[:redirect_url]
      first_char = params[:redirect_url].index('?').nil? ? '?' : '&'
      redirect_to "#{params[:redirect_url]}#{first_char}result_code=#{result_code}&email=#{params[:email]}"
    elsif result_code.to_i.zero?
      render text: "#{params[:email]} successfully added to the #{feedback_group.url} qidiq feedback group."
    else
      render text: "Failed to add #{params[:email]} to the #{feedback_group.url} qidiq feedback group."
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feedback_groups_helper.rb
module FeedbackGroupsHelper
end

app/views/feedback_groups/_form.html.erb
<%= form_for(@feedback_group) do |f| %>
  <% if @feedback_group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feedback_group.errors.count, "error") %> prohibited this feedback_group from being saved:</h2>

      <ul>
      <% @feedback_group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :api_key %><br />
    <%= f.text_field :api_key %>
  </div>
  <div class="field">
    <%= f.label :explanation %><br />
    <%= f.text_field :explanation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/feedback_groups/edit.html.erb
<h1>Editing Feedback Group</h1>

<%= render 'form' %>

<%= link_to 'Show', @feedback_group %> |
<%= link_to 'Back', feedback_groups_path %>

app/views/feedback_groups/index.html.erb
<% if current_user %>
  <h1>Listing Feedback Groups</h1>

  <table>
    <tr>
      <th>User</th>
      <th>Url</th>
      <th>Api key</th>
      <th>Explanation</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>

  <% @feedback_groups.each do |feedback_group| %>
    <tr>
      <td><%= feedback_group.user_id %></td>
      <td><%= feedback_group.url %></td>
      <td><%= feedback_group.api_key %></td>
      <td><%= feedback_group.explanation %></td>
      <td><%= link_to 'Show', feedback_group %></td>
      <td><%= link_to 'Edit', edit_feedback_group_path(feedback_group) %></td>
      <td><%= link_to 'Destroy', feedback_group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </table>

  <br />

  <%= link_to 'New Feedback group', new_feedback_group_path %>
<% end %>

app/views/feedback_groups/new.html.erb
<h1>New Feedback Group</h1>

<%= render 'form' %>

<%= link_to 'Back', feedback_groups_path %>

app/views/feedback_groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Url:</b>
  <%= @feedback_group.url %>
</p>

<p>
  <b>Api key:</b>
  <%= @feedback_group.api_key %>
</p>

<p>
  <b>Explanation:</b>
  <%= @feedback_group.explanation %>
</p>

<p>
  <b>Import POST URL:</b>
  <%= @import_post_url %>
</p>


<%= link_to 'Edit', edit_feedback_group_path(@feedback_group) %> |
<%= link_to 'Back', feedback_groups_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Qidiq API Importer Setup</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="user_nav">
    <% if user_signed_in? %>
      Signed in as <%= current_user.email %>. Not you?
      <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>
    <% end %>
  </div>
  <h1>Qidiq API Importer Setup</h1>
<%= yield %>

</body>
</html>